blueprint:
  name: ZHA - Moes Smart Knob for lights
  description: 'Control lights with a Moes Smart Knob.
  
    The knob functions in 2 modes: Command and Event/Scene. To switch between them, triple click the center button
    
    Command mode:
    1. Single Press
    2. Rotate Left/Right to dim
    3. Rotate Left/Right while pressing the center button to dim a different light(if prefered)

    Event/Scene mode:
    1. Single Press
    2. Double Press
    3. Long Press (Hold for about 4 seconds then release)

    Original blueprints by seamus65 (https://gist.github.com/seamus65/939a147634942dd885c8704334627f93).
    and
    JoryHogeveen (https://github.com/JoryHogeveen/HomeAssistantConfig/blob/c97016bee95cb13a7437087b994665fe609873cf/blueprints/automation/tuya/tuya-TS004F-knob.yaml)

    Improved by GonzaloAlbito (https://gist.github.com/gonzaloalbito/3dc06702e941e08298ea9bfade731731).

    Reorganized by Dreamscent(0x4a)

    Event Rotate left/right is a little laggy and wonky, 
    So it is better to use call service -> light.turn on -> brightness step(%) at around 20%

    Version 2022-05-30.'
  domain: automation
  input:
    remote:
      name: Remote
      description: Moes Knob to use
      selector:
        device:
          integration: zha
          manufacturer: _TZ3000_qja6nq5z
          model: TS004F
          multiple: false
    # event mode starts here
    press_short:
      name: Short Press (Event/Scene mode)
      selector:
        action: {}
      default: []
    press_double:
      name: Double Press (Event/Scene mode)
      selector:
        action: {}
      default: []
    press_long:
      name: Long Press (Event/Scene mode)
      selector:
        action: {}
      default: []
    rotate_left:
      name: Rotate Left (Event/Scene mode)
      selector:
        action: {}
      default: []
    rotate_right:
      name: Rotate Right (Event/Scene mode)
      selector:
        action: {}
      default: []
  source_url: https://github.com/Dreamscent/HomeIsWhereTheSmartIs/blob/main/Home%20Assistant/Blueprints/ZHA_Tuya_Smart_Knob.yaml
mode: queued
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote
action:
- variables:
    # same for both
    command: '{{ trigger.event.data.command }}'
    cluster_id: '{{ trigger.event.data.cluster_id }}'
    endpoint_id: '{{ trigger.event.data.endpoint_id }}'
    mode: '{% if command != ''toggle'' %} {{ trigger.event.data.args[0] }} {% endif
      %}'
    # jory stuff
    args: '{{ trigger.event.data.args }}'
    direction: '{% if trigger.event.data.args[0] == 0 %} 0 {% elif trigger.event.data.args[0]
      == 1 %} 1 {% elif trigger.event.data.args[0] == 3 %} 3 {% endif %}'
    value: '{% if trigger.event.data.args[1] %} {{ trigger.event.data.args[1] / 2
      }} {% endif %}'
    speed: '{% if trigger.event.data.args[2] == 1 %} 0.5 {% else %} 0 {% endif %}'

- choose:
# event mode
  - conditions:
    - '{{ command == ''remote_button_short_press'' }}'
    sequence: !input press_short
  - conditions:
    - '{{ command == ''remote_button_double_press'' }}'
    sequence: !input press_double
  - conditions:
    - '{{ command == ''remote_button_long_press'' }}'
    sequence: !input press_long
  - conditions:
    - '{{ command == ''left'' }}'
    sequence: !input rotate_left
  - conditions:
    - '{{ command == ''right'' }}'
    sequence: !input rotate_right
