blueprint:
  name: ZHA - Moes Smart Knob for lights
  description: 'Updated automation for Moes Smart Knob supporting single press and step dimming.'
  domain: automation
  input:
    remote:
      name: Remote
      selector:
        device:
          integration: zha
    light:
      name: Light(s)
      selector:
        target:
          entity:
          - domain:
            - light
    step_percent:
      name: Light step
      selector:
        number:
          mode: slider
          min: 1.0
          max: 100.0
          step: 1.0
      default: 10

trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote

action:
- variables:
    command: '{{ trigger.event.data.command }}'
    cluster_id: '{{ trigger.event.data.cluster_id }}'
    step_mode: '{{ trigger.event.data.params.step_mode | int }}'
    step_size: '{{ trigger.event.data.params.step_size | float }}'
    step_percent: '{{ step_size / 255 * 100 }}'

- choose:
  - conditions:
    - '{{ cluster_id == 6 }}'
    - '{{ command == "toggle" }}'
    sequence:
      - service: light.toggle
        target: !input light
  
  - conditions:
    - '{{ cluster_id == 8 }}'
    - '{{ command == "step" }}'
    sequence:
      - service: light.turn_on
        target: !input light
        data:
          brightness_step_pct: '{{ step_percent if step_mode == 0 else -step_percent }}'
          transition: 0.5
